language: java
jdk:
  - oraclejdk8
sudo: false
notifications:
  email: false
  irc:
    channels:
      - "irc.spi.gt#techcable"
before_install:
  - git config --global user.email "travis-ci@travis-ci.org"
  - git config --global user.name "Travis CI"
  - ./prepare-build.sh
after_success:
  - ./package.sh
cache:
  directories:
    - '$HOME/.m2/repository'
    - 'work'

# Install bsdiff
addons:
  apt:
    packages:
      - bsdiff

# Clear build results from the cache
before_cache:
  - 'rm -rf work/Paperclip'
  - 'rm -rf $HOME/.m2/repository/net/techcable/tacospigot'
